/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mycompany.oyun;

import java.awt.Font;
import javax.swing.ImageIcon;
import static mycompany.oyun.userID.oyuncuKartDizisi;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static mycompany.oyun.savas.i;

/**
 *
 * @author minth
 */
public class savasAni extends javax.swing.JFrame {
    
		ImageIcon ucak = new ImageIcon("Ucak.png");
    ImageIcon kfs = new ImageIcon("Kfs.png");
    ImageIcon obus = new ImageIcon("Obus.png");
    ImageIcon firka = new ImageIcon("Firkateyn.png");
    ImageIcon sida = new ImageIcon("Sida.png");
    ImageIcon siha = new ImageIcon("Siha.png");
    ImageIcon bos = new ImageIcon("bos.png");
    ImageIcon kapa = new ImageIcon("kapali.png");

    KartSec kart = new KartSec();
    userID user = new userID();

    
    public static int i = 1;
    
    /**
     * Creates new form savasAni
     */
    public savasAni() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 26, 29));
        jPanel1.setForeground(new java.awt.Color(26, 26, 29));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VS");

        jButton1.setBackground(new java.awt.Color(83, 100, 147));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(236, 223, 204));
        jButton1.setText("DEVAM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("jLabel9");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1)))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(90, 90, 90))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        
        
        
        if((user.oyuncuKartDizisi.get(0).dayaniklik >= 0 || user.oyuncuKartDizisi.get(1).dayaniklik >= 0 || user.oyuncuKartDizisi.get(2).dayaniklik >= 0
	         		||	user.oyuncuKartDizisi.get(3).dayaniklik >= 0 || user.oyuncuKartDizisi.get(4).dayaniklik >= 0 || user.oyuncuKartDizisi.get(5).dayaniklik >=0 ||
	         		user.oyuncuKartDizisi.get(6).dayaniklik >=0 || user.oyuncuKartDizisi.get(7).dayaniklik >=0 || user.oyuncuKartDizisi.get(8).dayaniklik >=0 || 
	         		user.oyuncuKartDizisi.get(9).dayaniklik >=0 || user.oyuncuKartDizisi.get(10).dayaniklik >=0 || user.oyuncuKartDizisi.get(11).dayaniklik >=0) && 
	         		(user.bilgisayarKartDizisi.get(0).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(1).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(2).dayaniklik >= 0
	         		|| user.bilgisayarKartDizisi.get(3).dayaniklik >=0  || user.bilgisayarKartDizisi.get(4).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(5).dayaniklik >=0 ||
	         		user.bilgisayarKartDizisi.get(6).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(7).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(8).dayaniklik >= 0 ||
	         		user.bilgisayarKartDizisi.get(9).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(10).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(11).dayaniklik >= 0) && (savas.i!=5)) 
                                {
	  			  new KartSec().setVisible(true);
         
       //1.kart
         if(oyuncuKartDizisi.get(0).isim == "Ucak")
         {    KartSec.jLabel1.setIcon(ucak);
         }else if (oyuncuKartDizisi.get(0).isim == "Siha")
               {    KartSec.jLabel1.setIcon(siha);
         } else if (oyuncuKartDizisi.get(0).isim == "Sida")
               {    KartSec.jLabel1.setIcon(sida);
         } else if (oyuncuKartDizisi.get(0).isim == "Firkateyn")
               {    KartSec.jLabel1.setIcon(firka);
         } else if (oyuncuKartDizisi.get(0).isim == "Obus")
               {    KartSec.jLabel1.setIcon(obus);
         } else if (oyuncuKartDizisi.get(0).isim == "Kfs")
               {    KartSec.jLabel1.setIcon(kfs);
         }else if (oyuncuKartDizisi.get(0).isim == null)
               {    KartSec.jLabel1.setIcon(bos);
         }
         //2.kart
         if(oyuncuKartDizisi.get(1).isim == "Ucak")
         {    KartSec.jLabel2.setIcon(ucak);
         }else if (oyuncuKartDizisi.get(1).isim == "Siha")
               {    KartSec.jLabel2.setIcon(siha);
         } else if (oyuncuKartDizisi.get(1).isim == "Sida")
               {    KartSec.jLabel2.setIcon(sida);
         } else if (oyuncuKartDizisi.get(1).isim == "Firkateyn")
               {    KartSec.jLabel2.setIcon(firka);
         } else if (oyuncuKartDizisi.get(1).isim == "Obus")
               {    KartSec.jLabel2.setIcon(obus);
         } else if (oyuncuKartDizisi.get(1).isim == "Kfs")
               {    KartSec.jLabel2.setIcon(kfs);
         }else if (oyuncuKartDizisi.get(1).isim == null)
               {    KartSec.jLabel2.setIcon(bos);
         }
         //3.kart
         if(oyuncuKartDizisi.get(2).isim == "Ucak")
         {    KartSec.jLabel3.setIcon(ucak);
         }else if (oyuncuKartDizisi.get(2).isim == "Siha")
               {    KartSec.jLabel3.setIcon(siha);
         } else if (oyuncuKartDizisi.get(2).isim == "Sida")
               {    KartSec.jLabel3.setIcon(sida);
         } else if (oyuncuKartDizisi.get(2).isim == "Firkateyn")
               {    KartSec.jLabel3.setIcon(firka);
         } else if (oyuncuKartDizisi.get(2).isim == "Obus")
               {    KartSec.jLabel3.setIcon(obus);
         } else if (oyuncuKartDizisi.get(2).isim == "Kfs")
               {    KartSec.jLabel3.setIcon(kfs);
         }else if (oyuncuKartDizisi.get(2).isim == null)
               {    KartSec.jLabel3.setIcon(bos);
         }
         //4.kart
         if(oyuncuKartDizisi.get(3).isim == "Ucak")
         {    KartSec.jLabel4.setIcon(ucak);
         }else if (oyuncuKartDizisi.get(3).isim == "Siha")
               {    KartSec.jLabel4.setIcon(siha);
         } else if (oyuncuKartDizisi.get(3).isim == "Sida")
               {    KartSec.jLabel4.setIcon(sida);
         } else if (oyuncuKartDizisi.get(3).isim == "Firkateyn")
               {    KartSec.jLabel4.setIcon(firka);
         } else if (oyuncuKartDizisi.get(3).isim == "Obus")
               {    KartSec.jLabel4.setIcon(obus);
         } else if (oyuncuKartDizisi.get(3).isim == "Kfs")
               {    KartSec.jLabel4.setIcon(kfs);
         }else if (oyuncuKartDizisi.get(3).isim == null)
               {    KartSec.jLabel4.setIcon(bos);
         }
         //5.kart
         if(oyuncuKartDizisi.get(4).isim == "Ucak")
         {    KartSec.jLabel5.setIcon(ucak);
         }else if (oyuncuKartDizisi.get(4).isim == "Siha")
               {    KartSec.jLabel5.setIcon(siha);
         } else if (oyuncuKartDizisi.get(4).isim == "Sida")
               {    KartSec.jLabel5.setIcon(sida);
         } else if (oyuncuKartDizisi.get(4).isim == "Firkateyn")
               {    KartSec.jLabel5.setIcon(firka);
         } else if (oyuncuKartDizisi.get(4).isim == "Obus")
               {    KartSec.jLabel5.setIcon(obus);
         } else if (oyuncuKartDizisi.get(4).isim == "Kfs")
               {    KartSec.jLabel5.setIcon(kfs);
         }else if (oyuncuKartDizisi.get(4).isim == null)
               {    KartSec.jLabel5.setIcon(bos);
         }
         //6.kart
         if(oyuncuKartDizisi.get(5).isim == "Ucak")
         {    KartSec.jLabel6.setIcon(ucak);
         }else if (oyuncuKartDizisi.get(5).isim == "Siha")
               {    KartSec.jLabel6.setIcon(siha);
         } else if (oyuncuKartDizisi.get(5).isim == "Sida")
               {    KartSec.jLabel6.setIcon(sida);
         } else if (oyuncuKartDizisi.get(5).isim == "Firkateyn")
               {    KartSec.jLabel6.setIcon(firka);
         } else if (oyuncuKartDizisi.get(5).isim == "Obus")
               {    KartSec.jLabel6.setIcon(obus);
         } else if (oyuncuKartDizisi.get(5).isim == "Kfs")
               {    KartSec.jLabel6.setIcon(kfs);
         }else if (oyuncuKartDizisi.get(5).isim == null)
               {    KartSec.jLabel6.setIcon(bos);
         }
         
         if(oyuncuKartDizisi.get(6).isim == "Ucak")
         {    KartSec.jLabel30.setIcon(ucak);
         }else if (oyuncuKartDizisi.get(6).isim == "Siha")
               {    KartSec.jLabel30.setIcon(siha);
         } else if (oyuncuKartDizisi.get(6).isim == "Sida")
               {    KartSec.jLabel30.setIcon(sida);
         } else if (oyuncuKartDizisi.get(6).isim == "Firkateyn")
               {    KartSec.jLabel30.setIcon(firka);
         } else if (oyuncuKartDizisi.get(6).isim == "Obus")
               {    KartSec.jLabel30.setIcon(obus);
         } else if (oyuncuKartDizisi.get(6).isim == "Kfs")
               {    KartSec.jLabel30.setIcon(kfs);
         }else if (oyuncuKartDizisi.get(6).isim == null)
               {    KartSec.jLabel30.setIcon(bos);
         }
         
         if(oyuncuKartDizisi.get(7).isim == "Ucak")
         {    KartSec.jLabel29.setIcon(ucak);
         }else if (oyuncuKartDizisi.get(7).isim == "Siha")
               {    KartSec.jLabel29.setIcon(siha);
         } else if (oyuncuKartDizisi.get(7).isim == "Sida")
               {    KartSec.jLabel29.setIcon(sida);
         } else if (oyuncuKartDizisi.get(7).isim == "Firkateyn")
               {    KartSec.jLabel29.setIcon(firka);
         } else if (oyuncuKartDizisi.get(7).isim == "Obus")
               {    KartSec.jLabel29.setIcon(obus);
         } else if (oyuncuKartDizisi.get(7).isim == "Kfs")
               {    KartSec.jLabel29.setIcon(kfs);
         }else if (oyuncuKartDizisi.get(7).isim == null)
               {    KartSec.jLabel29.setIcon(bos);
         }
         
         if(oyuncuKartDizisi.get(8).isim == "Ucak")
         {    KartSec.jLabel7.setIcon(ucak);
         }else if (oyuncuKartDizisi.get(8).isim == "Siha")
               {    KartSec.jLabel7.setIcon(siha);
         } else if (oyuncuKartDizisi.get(8).isim == "Sida")
               {    KartSec.jLabel7.setIcon(sida);
         } else if (oyuncuKartDizisi.get(8).isim == "Firkateyn")
               {    KartSec.jLabel7.setIcon(firka);
         } else if (oyuncuKartDizisi.get(8).isim == "Obus")
               {    KartSec.jLabel7.setIcon(obus);
         } else if (oyuncuKartDizisi.get(8).isim == "Kfs")
               {    KartSec.jLabel7.setIcon(kfs);
         }else if (oyuncuKartDizisi.get(8).isim == null)
               {    KartSec.jLabel7.setIcon(bos);
         }
         
         if(oyuncuKartDizisi.get(9).isim == "Ucak")
         {    KartSec.jLabel8.setIcon(ucak);
         }else if (oyuncuKartDizisi.get(9).isim == "Siha")
               {    KartSec.jLabel8.setIcon(siha);
         } else if (oyuncuKartDizisi.get(9).isim == "Sida")
               {    KartSec.jLabel8.setIcon(sida);
         } else if (oyuncuKartDizisi.get(9).isim == "Firkateyn")
               {    KartSec.jLabel8.setIcon(firka);
         } else if (oyuncuKartDizisi.get(9).isim == "Obus")
               {    KartSec.jLabel8.setIcon(obus);
         } else if (oyuncuKartDizisi.get(9).isim == "Kfs")
               {    KartSec.jLabel8.setIcon(kfs);
         }else if (oyuncuKartDizisi.get(9).isim == null)
               {    KartSec.jLabel8.setIcon(bos);
               
         }
         
         if(oyuncuKartDizisi.get(10).isim == "Ucak")
{    KartSec.jLabel40.setIcon(ucak);
}else if (oyuncuKartDizisi.get(10).isim == "Siha")
{    KartSec.jLabel40.setIcon(siha);
} else if (oyuncuKartDizisi.get(10).isim == "Sida")
{    KartSec.jLabel40.setIcon(sida);
} else if (oyuncuKartDizisi.get(10).isim == "Firkateyn")
{    KartSec.jLabel40.setIcon(firka);
} else if (oyuncuKartDizisi.get(10).isim == "Obus")
{    KartSec.jLabel40.setIcon(obus);
} else if (oyuncuKartDizisi.get(10).isim == "Kfs")
{    KartSec.jLabel40.setIcon(kfs);
}else if (oyuncuKartDizisi.get(10).isim == null)
{    KartSec.jLabel40.setIcon(bos);
}

if(oyuncuKartDizisi.get(11).isim == "Ucak")
{    KartSec.jLabel39.setIcon(ucak);
}else if (oyuncuKartDizisi.get(11).isim == "Siha")
{    KartSec.jLabel39.setIcon(siha);
} else if (oyuncuKartDizisi.get(11).isim == "Sida")
{    KartSec.jLabel39.setIcon(sida);
} else if (oyuncuKartDizisi.get(11).isim == "Firkateyn")
{    KartSec.jLabel39.setIcon(firka);
} else if (oyuncuKartDizisi.get(11).isim == "Obus")
{    KartSec.jLabel39.setIcon(obus);
} else if (oyuncuKartDizisi.get(11).isim == "Kfs")
{    KartSec.jLabel39.setIcon(kfs);
}else if (oyuncuKartDizisi.get(11).isim == null)
{    KartSec.jLabel39.setIcon(bos);
}

KartSec.jLabel42.setIcon(kapa);
KartSec.jLabel43.setIcon(kapa);
KartSec.jLabel44.setIcon(kapa);

if(userID.oyuncuKartDizisi.get(10).dayaniklik>0) {
KartSec. jLabel32.setText("Dayaniklilik "+ userID.oyuncuKartDizisi.get(10).dayaniklik);
KartSec. jLabel33.setText("Vurus "+ userID.oyuncuKartDizisi.get(10).vurus);}
else
{ KartSec. jLabel32.setText("");
KartSec. jLabel33.setText("");}

if(userID.oyuncuKartDizisi.get(11).dayaniklik>0) {
KartSec. jLabel31.setText("Dayaniklilik "+ userID.oyuncuKartDizisi.get(11).dayaniklik);
KartSec. jLabel34.setText("Vurus "+ userID.oyuncuKartDizisi.get(11).vurus);}
else
{ KartSec. jLabel31.setText("");
KartSec. jLabel34.setText("");}
         
         
           if(userID.oyuncuKartDizisi.get(0).dayaniklik>0) {
           KartSec. jLabel9.setText("Dayaniklilik "+ userID.oyuncuKartDizisi.get(0).dayaniklik);
           KartSec. jLabel18.setText("Vurus "+ userID.oyuncuKartDizisi.get(0).vurus);}
         else
         { KartSec. jLabel9.setText("");
           KartSec. jLabel18.setText("");}




            if(userID.oyuncuKartDizisi.get(1).dayaniklik>0) { 
             KartSec. jLabel10.setText("Dayaniklilik "+ userID.oyuncuKartDizisi.get(1).dayaniklik);
           KartSec.jLabel17.setText("Vurus "+ userID.oyuncuKartDizisi.get(1).vurus);
}
           else
         { KartSec. jLabel10.setText("");
           KartSec. jLabel17.setText("");}


           if(userID.oyuncuKartDizisi.get(2).dayaniklik>0) { 
          KartSec. jLabel19.setText("Dayaniklilik "+ userID.oyuncuKartDizisi.get(2).dayaniklik);
           KartSec. jLabel12.setText("Vurus "+ userID.oyuncuKartDizisi.get(2).vurus); }
           else
         { KartSec. jLabel19.setText("");
           KartSec. jLabel12.setText("");}

           
          if(userID.oyuncuKartDizisi.get(3).dayaniklik>0) { 
             KartSec. jLabel13.setText("Dayaniklilik "+ userID.oyuncuKartDizisi.get(3).dayaniklik);
           KartSec. jLabel20.setText("Vurus "+ userID.oyuncuKartDizisi.get(3).vurus);}
          else
         { KartSec. jLabel13.setText("");
           KartSec. jLabel20.setText("");}

           
           if(userID.oyuncuKartDizisi.get(4).dayaniklik>0) { 
           KartSec. jLabel14.setText("Dayaniklilik "+ userID.oyuncuKartDizisi.get(4).dayaniklik);
           KartSec. jLabel21.setText("Vurus "+ userID.oyuncuKartDizisi.get(4).vurus);}
           else
         { KartSec. jLabel14.setText("");
           KartSec. jLabel21.setText("");}

           
           if(userID.oyuncuKartDizisi.get(5).dayaniklik>0) { 
           KartSec.jLabel15.setText("Dayaniklilik "+ userID.oyuncuKartDizisi.get(5).dayaniklik);
           KartSec.jLabel22.setText("Vurus "+ userID.oyuncuKartDizisi.get(5).vurus);}
             else
         { KartSec. jLabel15.setText("");
           KartSec. jLabel22.setText("");}

           if(userID.oyuncuKartDizisi.get(6).dayaniklik>0) { 
           KartSec.jLabel16.setText("Dayaniklilik "+ userID.oyuncuKartDizisi.get(6).dayaniklik);
           KartSec.jLabel23.setText("Vurus "+ userID.oyuncuKartDizisi.get(5).vurus);}
                  else
         { KartSec. jLabel16.setText("");
           KartSec. jLabel23.setText("");}

           if(userID.oyuncuKartDizisi.get(7).dayaniklik>0) { 
                   KartSec.jLabel11.setText("Dayaniklilik "+ userID.oyuncuKartDizisi.get(7).dayaniklik);
           KartSec.jLabel24.setText("Vurus "+ userID.oyuncuKartDizisi.get(5).vurus);}
                     else
         { KartSec. jLabel11.setText("");
           KartSec. jLabel24.setText("");}

                   if(userID.oyuncuKartDizisi.get(8).dayaniklik>0) { 
                  KartSec.jLabel25.setText("Dayaniklilik "+ userID.oyuncuKartDizisi.get(8).dayaniklik);
           KartSec.jLabel26.setText("Vurus "+ userID.oyuncuKartDizisi.get(5).vurus);}
                     else
         { KartSec. jLabel25.setText("");
           KartSec. jLabel26.setText("");}

           if(userID.oyuncuKartDizisi.get(9).dayaniklik>0) { 
                   KartSec.jLabel27.setText("Dayaniklilik "+ userID.oyuncuKartDizisi.get(9).dayaniklik);
           KartSec.jLabel28.setText("Vurus "+ userID.oyuncuKartDizisi.get(9).vurus);}
           else
         { KartSec. jLabel27.setText("");
           KartSec. jLabel28.setText("");}
         
       
         
           
           i++;
        
      this.dispose();
	  				
	  			}
        
                                   
        
        
        else {                                      
        	
        	 String dosyaAdi = "C:\\Users\\minth\\Desktop\\SavasAdimlari.txt";
                 if(i==5) {
        		if(user.oyuncuPuan > user.bilgisayarPuan) {
        			try (BufferedWriter bw = new BufferedWriter(new FileWriter(dosyaAdi,true))) {
        			    bw.newLine();
        			    bw.write("OYUNCUNUN SKORU BİLGİSAYARDAN YÜKSEKTİR . ");
        				bw.newLine();
        				bw.write("OYUNCU SAVAŞI KAZANDIII !!! ");
        				bw.newLine();
                                         JLabel message = new JLabel("SAVASI OYUNCU KAZANDI");
                                                 message.setFont(new Font("Arial",Font.BOLD,48));
                                                 JOptionPane.showMessageDialog(null,message);
        			}catch(IOException e) {
        				System.out.println("Bir hata oluştu : " + e.getMessage());
        			}
        		}else if(user.bilgisayarPuan > user.oyuncuPuan) {
        			try (BufferedWriter bw = new BufferedWriter(new FileWriter(dosyaAdi,true))) {
        				bw.newLine();
        				bw.write("BİLGİSAYARIN SKORU OYUNCUDAN YÜKSEKTİR.");
        				bw.newLine();
        				bw.write("BİLGİSAYAR SAVAŞI KAZANDIII !!!");
        				bw.newLine();
        				  JLabel message = new JLabel("SAVASI BILGISAYAR KAZANDI");
                                                 message.setFont(new Font("Arial",Font.BOLD,48));
                                                 JOptionPane.showMessageDialog(null,message);
        			}catch(IOException e) {
        				System.out.println("Bir hata oluştu : " + e.getMessage());
        		}
        	}else if(user.oyuncuPuan == user.bilgisayarPuan) {
        		try (BufferedWriter bw = new BufferedWriter(new FileWriter(dosyaAdi,true))) {
    				bw.newLine();
    				bw.newLine();
    				bw.write("İki Tarafında Skorları Eşit . Durum Berabere. Kalan Kartlarin Dayanıklıklarına Bakılacak.");
    				bw.newLine();
    				
    			}catch(IOException e) {
    				System.out.println("Bir hata oluştu : " + e.getMessage());
    		}
        		
        		
        		
        		if(savas.bilgisayarKalanKartDayaniklilik > savas.oyuncuKalanKartDayaniklilik) {
        			try (BufferedWriter bw = new BufferedWriter(new FileWriter(dosyaAdi,true))) {
        				bw.newLine();
        				user.bilgisayarPuan += (savas.bilgisayarKalanKartDayaniklilik - savas.oyuncuKalanKartDayaniklilik) ;     						
        			    bw.write("Hesaplamalar Sonucu Yeni Skorlar : \n");
        				bw.write("Bilgisayar skor : " + user.bilgisayarPuan);
        				bw.newLine();
        				bw.write("Oyuncu Skor : " + user.oyuncuPuan);
        				bw.newLine();
        				bw.newLine();
        				bw.write("BİLGİSAYAR SAVAŞI KAZANDIII !!!");
        				bw.newLine();   
                                          JLabel message = new JLabel("SAVASI BILGISAYAR KAZANDI");
                                                 message.setFont(new Font("Arial",Font.BOLD,48));
                                                 JOptionPane.showMessageDialog(null,message);
        			}catch(IOException e) {
        				System.out.println("Bir hata oluştu : " + e.getMessage());
        		}
        		}else if(savas.oyuncuKalanKartDayaniklilik > savas.bilgisayarKalanKartDayaniklilik) {
        			try (BufferedWriter bw = new BufferedWriter(new FileWriter(dosyaAdi,true))) {
        				bw.newLine();
        				user.oyuncuPuan += (savas.oyuncuKalanKartDayaniklilik - savas.bilgisayarKalanKartDayaniklilik) ;     						
        			    bw.write("Hesaplamalar Sonucu Yeni Skorlar : \n");
        				bw.write("Bilgisayar skor : " + user.bilgisayarPuan);
        				bw.newLine();
        				bw.write("Oyuncu Skor : " + user.oyuncuPuan);
        				bw.newLine();
        				bw.newLine();
        				bw.write("OYUNCU SAVAŞI KAZANDIII !!!");
        				bw.newLine();   
                                          JLabel message = new JLabel("SAVASI OYUNCU KAZANDI");
                                                 message.setFont(new Font("Arial",Font.BOLD,48));
                                                 JOptionPane.showMessageDialog(null,message);
        			}catch(IOException e) {
        				System.out.println("Bir hata oluştu : " + e.getMessage());
        		}
        		}else if(savas.bilgisayarKalanKartDayaniklilik == savas.oyuncuKalanKartDayaniklilik) {
        			try (BufferedWriter bw = new BufferedWriter(new FileWriter(dosyaAdi,true))) {
        				bw.newLine();
        				bw.write("Yapılan Hesaplamalar Sonucu Skorlar Değişmedi .");
        				bw.newLine();
        				bw.write("OYUNUN SONUCU BERABERE !!!");
        				bw.newLine();   				
        			}catch(IOException e) {
        				System.out.println("Bir hata oluştu : " + e.getMessage());
        		}
        		}
        	}
        	}else if((user.oyuncuKartDizisi.get(0).dayaniklik >= 0 || user.oyuncuKartDizisi.get(1).dayaniklik >= 0 || user.oyuncuKartDizisi.get(2).dayaniklik >= 0
	         		||	user.oyuncuKartDizisi.get(3).dayaniklik >= 0 || user.oyuncuKartDizisi.get(4).dayaniklik >= 0 || user.oyuncuKartDizisi.get(5).dayaniklik >=0 ||
	         		user.oyuncuKartDizisi.get(6).dayaniklik >=0 || user.oyuncuKartDizisi.get(7).dayaniklik >=0 || user.oyuncuKartDizisi.get(8).dayaniklik >=0 || 
	         		user.oyuncuKartDizisi.get(9).dayaniklik >=0 || user.oyuncuKartDizisi.get(10).dayaniklik >=0 || user.oyuncuKartDizisi.get(11).dayaniklik >=0) == false) {
        		try (BufferedWriter bw = new BufferedWriter(new FileWriter(dosyaAdi,true))) {
    				bw.newLine();
    				bw.write("Oyuncunun Elindeki Kartlar Tükendi .");
    				bw.newLine();
    				bw.write("BİLGİSAYAR SAVAŞI KAZANDI !!!");
    				bw.newLine();   		
                                  JLabel message = new JLabel("SAVASI BILGISAYAR KAZANDI");
                                                 message.setFont(new Font("Arial",Font.BOLD,48));
                                                 JOptionPane.showMessageDialog(null,message);
    			}catch(IOException e) {
    				System.out.println("Bir hata oluştu : " + e.getMessage());
    		}
        	}else if((user.bilgisayarKartDizisi.get(0).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(1).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(2).dayaniklik >= 0
	         		|| user.bilgisayarKartDizisi.get(3).dayaniklik >=0  || user.bilgisayarKartDizisi.get(4).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(5).dayaniklik >=0 ||
	         		user.bilgisayarKartDizisi.get(6).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(7).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(8).dayaniklik >= 0 ||
	         		user.bilgisayarKartDizisi.get(9).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(10).dayaniklik >= 0 || user.bilgisayarKartDizisi.get(11).dayaniklik >= 0) == false) {
        		try (BufferedWriter bw = new BufferedWriter(new FileWriter(dosyaAdi,true))) {
    				bw.newLine();
    				bw.write("Bilgisayarın Elindeki Kartlar Tükendi .");
    				bw.newLine();
    				bw.write("OYUNCU SAVAŞI KAZANDI !!!");
    				bw.newLine();  
  JLabel message = new JLabel("SAVASI OYUNCU KAZANDI");
                                                 message.setFont(new Font("Arial",Font.BOLD,48));
                                                 JOptionPane.showMessageDialog(null,message);                              
    			}catch(IOException e) {
    				System.out.println("Bir hata oluştu : " + e.getMessage());
    		}
        	}
        	

	  				new Kapanis().setVisible(true);
                                        this.dispose();
	  			
        
        
        }
        
        
        
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents2() {

     
    }// </editor-fold>                        

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(savasAni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(savasAni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(savasAni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(savasAni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new savasAni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
   public static javax.swing.JLabel jLabel5;
   public static javax.swing.JLabel jLabel6;
   public static javax.swing.JLabel jLabel7;
   public static javax.swing.JLabel jLabel8;
   public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
